---
  env:
    browser: true
    node: true
  extends: eslint:recommended
  plugins:
  - es5
  rules:
    max-len:
      - error
      - 80
    no-trailing-spaces: error
    indent:
      - error
      - 2
    semi: error
